const fs = require('fs');
let content = fs.readFileSync('src/components/views/BridgeView.tsx', 'utf8');

const regex = /<button\n\s*onClick=\{reverseDirection\}\n\s*className="w-8 h-8 rounded-full bg-white border border-slate-200 shadow-sm flex items-center justify-center text-slate-600 hover:text-slate-900 hover:border-slate-300 transition-all active:scale-95"\n\s*<\/div>\n\s*<div>\n\s*<div className="flex items-center justify-between">\n\s*<div className="flex items-center gap-2 bg-slate-50\/80 border border-slate-100 rounded-full px-3 py-1\.5 shrink-0">\n\s*<div className="w-5 h-5 bg-blue-100 rounded-full flex items-center justify-center">\n\s*<Coins size=\{12\} className="text-blue-500" \/>\n\s*<\/div>\n\s*<span className="font-bold text-slate-600 text-sm">USDC<\/span>\n\s*<\/div>\n\s*<input\n\s*type="number"\n\s*placeholder="0\.00"\n\s*value=\{amount\}\n\s*onChange=\{\(e\) => setAmount\(e\.target\.value\)\}\n\s*className="w-full min-w-0 flex-1 bg-slate-50 border border-slate-200 rounded-xl px-4 py-2 text-2xl font-bold text-right text-slate-800 outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-400\/20 placeholder:text-slate-300 ml-4 transition-all"\n\s*\/>\n\s*<\/div>\n\s*<\/div>\n\s*<\/div>\n\s*\{\/\* Reverse Button \*\/}\n\s*<div className="flex justify-center -my-4 relative z-20">\n\s*<button\n\s*onClick=\{reverseDirection\}\n\s*className="w-8 h-8 rounded-full bg-white border border-slate-200 shadow-sm flex items-center justify-center text-slate-600 hover:text-slate-900 hover:border-slate-300 transition-all active:scale-95"\n\s*>/;

content = content.replace(regex, `          >`);
content = content.replace(`{/* To Network */}\n        <div className="bg-white border border-slate-200 rounded-[1.5rem] p-4 mt-2 mb-6 shadow-sm">`, `{/* To Network */}\n        <div className="bg-white border border-slate-200 rounded-[1.25rem] p-4 mt-2 mb-4 shadow-sm">`);
content = content.replace(`{/* To Network */}\n        <div className="bg-white border border-slate-200 rounded-[1.25rem] p-4 mt-2 mb-6 shadow-sm">`, `{/* To Network */}\n        <div className="bg-white border border-slate-200 rounded-[1.25rem] p-4 mt-2 mb-4 shadow-sm">`);

fs.writeFileSync('src/components/views/BridgeView.tsx', content, 'utf8');
